id: medcom.fhir.dk.messagedefinitions
canonical: http://medcomfhir.dk/ig/messagedefinitions
name: dk-medcom-messagedefinitions
title: MedCom MessageDefinitions
description: The MessageDefinitions IG contains the collection of all MedCom MessageDefinitions inherited from MedComMessagingMessageDefinitionFHIR related to specific MedCom FHIR messaging standards
status: active # draft | active | retired | unknown
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: release # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: MedCom
  url: http://www.medcom.dk
contact:
  - name: MedCom FHIR Team
    telecom:
      - system: email
        value: fhir@medcom.dk
        use: work
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"

dependencies:
  hl7.fhir.dk.core: 3.2.0
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.messaging: 3.0.0
  medcom.fhir.dk.terminology: 1.8.1

parameters:  
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true

menu:
  Home: index.html
  Artifacts: artifacts.html

instanceOptions:
  manualSliceOrdering: true # true | false
